name: Generate posts.json

on:
  push:
    branches: [ main ]
    paths:
      - 'posts/**'

jobs:
  generate-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4

    - name: Generate posts.json
      run: |
        python .github/scripts/generate_posts_json.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add posts.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update posts.json" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
